---

name: Cleanup

on: 
  push: 
    branches: 
      - main
    paths:
      - '*.json'

jobs:
  dewit: 
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: cleanup

    steps:
      ## https://github.com/actions/checkout
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          path: cleanup

      - name: Fix and commit SmartQuotes
        id: cleanup
        run: |
          echo "PWD: $(pwd)"
          for JSON in $(ls *.json); do
            sed -i "s/’/'/g" $JSON
            sed -i 's/[”“]/"/g' $JSON
          done
          git config --local user.email "devon+github-actions[bot]@hubner.org"
          git config --local user.name "github-actions[bot]"
          git add -A *.json ; true
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "Fixing SmartQuotes" -a
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi


      ## https://github.com/ad-m/github-push-action
      - name: Push changes
        if: steps.cleanup.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: cleanup
